### ISSUE TITLE
run succesfully ,but i don't know how to use it.

### ISSUE THREAD

**Issue by alancpu** [ensan-hcl/macOS_IMKitSample_2021#4]
hello ensan

thanks for your share

I  run the sample on my mac with no issue.

but I can not find IMKitSample in the input source. so  I can not switch to it.

how can I  use the input method in my text editor?

**Comment by ensan-hcl** [comment]
Hello @alancpu .
Did you check **setting** > **keyboard** > **input source** > **English**?

This is the screenshot taken in my environment. I could find the input source here.
<img width="780" alt="image" src="https://user-images.githubusercontent.com/63481257/179750035-82421c9b-ecfb-4ca4-a94e-2693ca315593.png">

**Comment by mshuffett** [comment]
Didn't appear there for me.

In logs just says

2023-04-06 14:00:49.700737-0400 IMKitSample[6622:22318143] tried connection

**Comment by mshuffett** [comment]
I had to restart the computer for it to show up.

**Comment by ensan-hcl** [comment]
Oh I didn't know that case. I'll add your information to README.

**Comment by ensan-hcl** [comment]
Since there's no reaction form author, I'd like to close this issue. If there's any problem, feel free to re-open or create another issue.
